service: location-service-typescript

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10

package:
  include:
    - capitals.json

functions:
  location:
    handler: handler.endpoint
    events:
      - http:
          path: getNearestLocations/{latitude}/{longitude}
          method: get